## Действия с тензорами

Импортируем библиотеку PyTorch и проверяем её установленную версию.


In [1]:
import torch
torch.__version__

'2.12.0'

Создаём тензоры разных размерностей: 0D, 1D и 2D.


In [2]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

Выводим содержимое двумерного тензора.


In [3]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

Смотрим тип данных (dtype) элементов тензора.


In [4]:
tensor2d.dtype

torch.int64

Преобразуем тензор к типу float32 и выводим результат.


In [5]:
floatvec = tensor2d.to(torch.float32)
floatvec

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Получаем форму (shape) двумерного тензора.


In [6]:
tensor2d.shape

torch.Size([2, 3])

Меняем форму тензора с помощью view без изменения данных.


In [7]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

Транспонируем двумерный тензор, меняя местами строки и столбцы.


In [8]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Разные способы умножения матриц с т.з. синтаксиса


In [9]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [10]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

Логистрическая регрессия

In [24]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0]) # целевая метка
x1 = torch.tensor([1.1]) # входной признак
w1 = torch.tensor([2.2], requires_grad=True) # весовой параметр
b = torch.tensor([0.0], requires_grad=True) # единица смещения bias

z = x1 * w1 + b # вход сети
a = torch.sigmoid(z) # функция активация примененная ко входу (выход)

loss = F.binary_cross_entropy(a, y) # активация и выход

# grad_L_w1 = grad(loss, w1, retain_graph=True)
# grad_L_b = grad(loss, b, retain_graph=True)

# print(grad_L_w1)
# print(grad_L_b)

In [25]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## Реализация многослойных нейронных сетей