Импортируем библиотеку PyTorch и проверяем её установленную версию.


In [1]:
import torch
torch.__version__

'2.12.0+cpu'

Проверяем, доступно ли CUDA-ускорение (GPU) для вычислений.


In [2]:
torch.cuda.is_available()

False

Создаём тензоры разных размерностей: 0D, 1D и 2D.


In [3]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

Выводим содержимое двумерного тензора.


In [4]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

Смотрим тип данных (dtype) элементов тензора.


In [5]:
tensor2d.dtype

torch.int64

Преобразуем тензор к типу float32 и выводим результат.


In [6]:
floatvec = tensor2d.to(torch.float32)
floatvec

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Получаем форму (shape) двумерного тензора.


In [7]:
tensor2d.shape

torch.Size([2, 3])

Меняем форму тензора с помощью view без изменения данных.


In [8]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

Транспонируем двумерный тензор, меняя местами строки и столбцы.


In [9]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Разные способы умножения матриц с т.з. синтаксиса


In [10]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [12]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])